DROP TABLE IF EXISTS Kayttaja CASCADE;
DROP TABLE IF EXISTS Kilpailu CASCADE;
DROP TABLE IF EXISTS Kilpailija CASCADE;
DROP TABLE IF EXISTS Kirjaaja CASCADE;
DROP TABLE IF EXISTS Toimitsijarooli CASCADE;
DROP TABLE IF EXISTS Ajanmittauspiste CASCADE;
DROP TABLE IF EXISTS Osallistuja CASCADE;
DROP TABLE IF EXISTS Tulos CASCADE;